language: python

dist: xenial

branches:
  except:
      - pypy_symbolic

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
    - xvfb
    - gfortran
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev

before_install:
  - pip install -U --only-binary=numpy,scipy numpy scipy

# Install packages
install:
  - pip install numpy scipy matplotlib sympy nose setuptools coverage
  - pip install tabulate python-coveralls
  - python setup.py install

# Run the tests
script: xvfb-run nosetests -v -s --with-coverage --cover-package=ahkab tests/*/*.py

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

